CREATE TABLE VENUES(
	VENUE_ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
	NAME  VARCHAR(255),
	CITY  VARCHAR(255),
	STATE VARCHAR(255),
);

CREATE TABLE EVENTS(
	EVENT_ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255),
	DATE TIMESTAMP,
	VENUES_ID BIGINT,
	FOREIGN KEY(VENUES_ID) REFERENCES VENUES(VENUE_ID)
);